# Generated by Django 5.1 on 2024-09-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_tv_show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
