# Generated by Django 5.1 on 2024-09-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_new_tv_show_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_tv_show',
            name='audienceScore',
            field=models.CharField(default=109, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_tv_show',
            name='criticScore',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
