# Generated by Django 5.1 on 2024-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_new_tv_show_audiencescore_new_tv_show_criticscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_tv_show',
            name='audienceScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='new_tv_show',
            name='criticScore',
            field=models.IntegerField(),
        ),
    ]
