# Generated by Django 5.1 on 2024-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_new_tv_show_audiencescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_tv_show',
            name='last_episode_date',
            field=models.CharField(default=1231231, max_length=50),
            preserve_default=False,
        ),
    ]
