# Generated by Django 5.1 on 2024-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_new_tv_show_last_episode_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_tv_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_src', models.URLField()),
                ('last_episode_date', models.CharField(max_length=50)),
                ('criticScore', models.IntegerField()),
                ('audienceScore', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
