# Generated by Django 5.1.1 on 2024-10-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_new_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_movies',
            new_name='new_movie',
        ),
    ]
