# Generated by Django 5.1.1 on 2024-10-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_new_movies_new_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_movie',
            old_name='opening_date',
            new_name='last_episode_date',
        ),
    ]
