# Generated by Django 5.1.1 on 2024-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_opening_date_new_movie_last_episode_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_src', models.URLField()),
                ('last_episode_date', models.CharField(max_length=50)),
                ('criticScore', models.IntegerField()),
                ('audienceScore', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
