# Generated by Django 5.1.1 on 2024-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_series_on_hbo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='series_on_hbo',
            new_name='popular_on_hbo',
        ),
    ]
